services:
  dev:
    build: .
    volumes:
      - ./.opencode:/root/.config/opencode
      - ./.ocdata:/root/.local/share/opencode
      - .:/workspace_root
      - ./workspace:/workspace
      - ./templates:/templates:ro
      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
    ports:
      - 5173:5173
    environment:
      - DOCKER_HOST=tcp://daemon:2375
      - SSH_AUTH_SOCK=/tmp/ssh-agent.sock
      - GIT_URL=${GIT_URL}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - REPO_NAME=${REPO_NAME}
      - SUBFOLDER=${SUBFOLDER}
      - TEMPLATE_TYPE=${TEMPLATE_TYPE}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - daemon

  daemon:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_VERIFY=0
      - DOCKER_TLS_CERTDIR=
      - DOCKER_CERT_PATH=
      - HOST=tcp://0.0.0.0:2375
    volumes:
      - ./workspace:/workspace
      - docker_cache:/var/lib/docker

volumes:
  docker_cache:
